name: news_app_chatgpt
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  kartal: ^3.4.3
  provider: ^6.0.5
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2


flutter:
  uses-material-design: true

  assets:
    - assets/color/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Nantes
      fonts:
        - asset: assets/fonts/Nantes.ttf
    
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
    
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SFPro.ttf

flutter_gen:
  output: lib/products/generation/
  assets:
    enabled: true

  colors:
    inputs:
      - assets/color/colors.xml


